apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-windows
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-windows
  template:
    metadata:
      labels:
        app: hello-world-windows
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: hello-world
        image: k8syns/hello-world-windows:latest
        ports:
        - containerPort: 8080
