apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-windows
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-windows
  template:
    metadata:
      labels:
        app: hello-world-windows
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: hello-world
        image: k8syns/hello-world-windows:{{tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-windows
spec:
  type: ClusterIP
  selector:
    app: hello-world-windows
  ports:
  - name: http
    port: 80
    targetPort: 8080
